/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProfessionalsRouteImport } from './routes/professionals'
import { Route as LegislativeRouteImport } from './routes/legislative'
import { Route as JudgesRouteImport } from './routes/judges'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as CollabRouteImport } from './routes/collab'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersJoinRouteImport } from './routes/providers/join'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as PlaybooksMatrixRouteImport } from './routes/playbooks.matrix'
import { Route as PlaybooksLitigationRouteImport } from './routes/playbooks.litigation'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsRoute = ProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const LegislativeRoute = LegislativeRouteImport.update({
  id: '/legislative',
  path: '/legislative',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesRoute = JudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabRoute = CollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersJoinRoute = ProvidersJoinRouteImport.update({
  id: '/providers/join',
  path: '/providers/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksMatrixRoute = PlaybooksMatrixRouteImport.update({
  id: '/playbooks/matrix',
  path: '/playbooks/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksLitigationRoute = PlaybooksLitigationRouteImport.update({
  id: '/playbooks/litigation',
  path: '/playbooks/litigation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/admin/providers',
  path: '/admin/providers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/calendar': typeof CalendarRoute
  '/cases': typeof CasesRoute
  '/collab': typeof CollabRoute
  '/connections': typeof ConnectionsRoute
  '/donate': typeof DonateRoute
  '/judges': typeof JudgesRoute
  '/legislative': typeof LegislativeRoute
  '/professionals': typeof ProfessionalsRoute
  '/reviews': typeof ReviewsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/playbooks/litigation': typeof PlaybooksLitigationRoute
  '/playbooks/matrix': typeof PlaybooksMatrixRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/providers/join': typeof ProvidersJoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/calendar': typeof CalendarRoute
  '/cases': typeof CasesRoute
  '/collab': typeof CollabRoute
  '/connections': typeof ConnectionsRoute
  '/donate': typeof DonateRoute
  '/judges': typeof JudgesRoute
  '/legislative': typeof LegislativeRoute
  '/professionals': typeof ProfessionalsRoute
  '/reviews': typeof ReviewsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/playbooks/litigation': typeof PlaybooksLitigationRoute
  '/playbooks/matrix': typeof PlaybooksMatrixRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/providers/join': typeof ProvidersJoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/calendar': typeof CalendarRoute
  '/cases': typeof CasesRoute
  '/collab': typeof CollabRoute
  '/connections': typeof ConnectionsRoute
  '/donate': typeof DonateRoute
  '/judges': typeof JudgesRoute
  '/legislative': typeof LegislativeRoute
  '/professionals': typeof ProfessionalsRoute
  '/reviews': typeof ReviewsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/playbooks/litigation': typeof PlaybooksLitigationRoute
  '/playbooks/matrix': typeof PlaybooksMatrixRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/providers/join': typeof ProvidersJoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advertise'
    | '/calendar'
    | '/cases'
    | '/collab'
    | '/connections'
    | '/donate'
    | '/judges'
    | '/legislative'
    | '/professionals'
    | '/reviews'
    | '/admin/providers'
    | '/playbooks/litigation'
    | '/playbooks/matrix'
    | '/providers/$id'
    | '/providers/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advertise'
    | '/calendar'
    | '/cases'
    | '/collab'
    | '/connections'
    | '/donate'
    | '/judges'
    | '/legislative'
    | '/professionals'
    | '/reviews'
    | '/admin/providers'
    | '/playbooks/litigation'
    | '/playbooks/matrix'
    | '/providers/$id'
    | '/providers/join'
  id:
    | '__root__'
    | '/'
    | '/advertise'
    | '/calendar'
    | '/cases'
    | '/collab'
    | '/connections'
    | '/donate'
    | '/judges'
    | '/legislative'
    | '/professionals'
    | '/reviews'
    | '/admin/providers'
    | '/playbooks/litigation'
    | '/playbooks/matrix'
    | '/providers/$id'
    | '/providers/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvertiseRoute: typeof AdvertiseRoute
  CalendarRoute: typeof CalendarRoute
  CasesRoute: typeof CasesRoute
  CollabRoute: typeof CollabRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DonateRoute: typeof DonateRoute
  JudgesRoute: typeof JudgesRoute
  LegislativeRoute: typeof LegislativeRoute
  ProfessionalsRoute: typeof ProfessionalsRoute
  ReviewsRoute: typeof ReviewsRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  PlaybooksLitigationRoute: typeof PlaybooksLitigationRoute
  PlaybooksMatrixRoute: typeof PlaybooksMatrixRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  ProvidersJoinRoute: typeof ProvidersJoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals': {
      id: '/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof ProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislative': {
      id: '/legislative'
      path: '/legislative'
      fullPath: '/legislative'
      preLoaderRoute: typeof LegislativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges': {
      id: '/judges'
      path: '/judges'
      fullPath: '/judges'
      preLoaderRoute: typeof JudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab': {
      id: '/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof CollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/join': {
      id: '/providers/join'
      path: '/providers/join'
      fullPath: '/providers/join'
      preLoaderRoute: typeof ProvidersJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks/matrix': {
      id: '/playbooks/matrix'
      path: '/playbooks/matrix'
      fullPath: '/playbooks/matrix'
      preLoaderRoute: typeof PlaybooksMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks/litigation': {
      id: '/playbooks/litigation'
      path: '/playbooks/litigation'
      fullPath: '/playbooks/litigation'
      preLoaderRoute: typeof PlaybooksLitigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvertiseRoute: AdvertiseRoute,
  CalendarRoute: CalendarRoute,
  CasesRoute: CasesRoute,
  CollabRoute: CollabRoute,
  ConnectionsRoute: ConnectionsRoute,
  DonateRoute: DonateRoute,
  JudgesRoute: JudgesRoute,
  LegislativeRoute: LegislativeRoute,
  ProfessionalsRoute: ProfessionalsRoute,
  ReviewsRoute: ReviewsRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  PlaybooksLitigationRoute: PlaybooksLitigationRoute,
  PlaybooksMatrixRoute: PlaybooksMatrixRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  ProvidersJoinRoute: ProvidersJoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
