/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SolicitorRouteImport } from './routes/solicitor'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProfessionalsRouteImport } from './routes/professionals'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalsRouteImport } from './routes/portals'
import { Route as LegislativeRouteImport } from './routes/legislative'
import { Route as JudgesRouteImport } from './routes/judges'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CourtDocsRouteImport } from './routes/court-docs'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as CollabRouteImport } from './routes/collab'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersJoinRouteImport } from './routes/providers/join'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as PortalsProfessionalRouteImport } from './routes/portals.professional'
import { Route as PortalsClientRouteImport } from './routes/portals/client'
import { Route as PortalsAgencyRouteImport } from './routes/portals.agency'
import { Route as PortalsAdvertiserRouteImport } from './routes/portals.advertiser'
import { Route as PlaybooksMatrixRouteImport } from './routes/playbooks.matrix'
import { Route as PlaybooksLitigationRouteImport } from './routes/playbooks.litigation'
import { Route as EmployeeTasksRouteImport } from './routes/employee.tasks'
import { Route as EmployeeDashboardRouteImport } from './routes/employee.dashboard'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminJudgesRouteImport } from './routes/admin.judges'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitorRoute = SolicitorRouteImport.update({
  id: '/solicitor',
  path: '/solicitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsRoute = ProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsRoute = PortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => rootRouteImport,
} as any)
const LegislativeRoute = LegislativeRouteImport.update({
  id: '/legislative',
  path: '/legislative',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesRoute = JudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtDocsRoute = CourtDocsRouteImport.update({
  id: '/court-docs',
  path: '/court-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabRoute = CollabRouteImport.update({
  id: '/collab',
  path: '/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersJoinRoute = ProvidersJoinRouteImport.update({
  id: '/providers/join',
  path: '/providers/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsProfessionalRoute = PortalsProfessionalRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => PortalsRoute,
} as any)
const PortalsClientRoute = PortalsClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => PortalsRoute,
} as any)
const PortalsAgencyRoute = PortalsAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => PortalsRoute,
} as any)
const PortalsAdvertiserRoute = PortalsAdvertiserRouteImport.update({
  id: '/advertiser',
  path: '/advertiser',
  getParentRoute: () => PortalsRoute,
} as any)
const PlaybooksMatrixRoute = PlaybooksMatrixRouteImport.update({
  id: '/playbooks/matrix',
  path: '/playbooks/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksLitigationRoute = PlaybooksLitigationRouteImport.update({
  id: '/playbooks/litigation',
  path: '/playbooks/litigation',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeTasksRoute = EmployeeTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeDashboardRoute = EmployeeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/admin/providers',
  path: '/admin/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJudgesRoute = AdminJudgesRouteImport.update({
  id: '/admin/judges',
  path: '/admin/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/cases': typeof CasesRoute
  '/collab': typeof CollabRoute
  '/connections': typeof ConnectionsRoute
  '/court-docs': typeof CourtDocsRoute
  '/donate': typeof DonateRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/judges': typeof JudgesRoute
  '/legislative': typeof LegislativeRoute
  '/portals': typeof PortalsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/professionals': typeof ProfessionalsRoute
  '/reviews': typeof ReviewsRoute
  '/solicitor': typeof SolicitorRoute
  '/trust': typeof TrustRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/playbooks/litigation': typeof PlaybooksLitigationRoute
  '/playbooks/matrix': typeof PlaybooksMatrixRoute
  '/portals/advertiser': typeof PortalsAdvertiserRoute
  '/portals/agency': typeof PortalsAgencyRoute
  '/portals/client': typeof PortalsClientRoute
  '/portals/professional': typeof PortalsProfessionalRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/providers/join': typeof ProvidersJoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/cases': typeof CasesRoute
  '/collab': typeof CollabRoute
  '/connections': typeof ConnectionsRoute
  '/court-docs': typeof CourtDocsRoute
  '/donate': typeof DonateRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/judges': typeof JudgesRoute
  '/legislative': typeof LegislativeRoute
  '/portals': typeof PortalsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/professionals': typeof ProfessionalsRoute
  '/reviews': typeof ReviewsRoute
  '/solicitor': typeof SolicitorRoute
  '/trust': typeof TrustRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/playbooks/litigation': typeof PlaybooksLitigationRoute
  '/playbooks/matrix': typeof PlaybooksMatrixRoute
  '/portals/advertiser': typeof PortalsAdvertiserRoute
  '/portals/agency': typeof PortalsAgencyRoute
  '/portals/client': typeof PortalsClientRoute
  '/portals/professional': typeof PortalsProfessionalRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/providers/join': typeof ProvidersJoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/cases': typeof CasesRoute
  '/collab': typeof CollabRoute
  '/connections': typeof ConnectionsRoute
  '/court-docs': typeof CourtDocsRoute
  '/donate': typeof DonateRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/judges': typeof JudgesRoute
  '/legislative': typeof LegislativeRoute
  '/portals': typeof PortalsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/professionals': typeof ProfessionalsRoute
  '/reviews': typeof ReviewsRoute
  '/solicitor': typeof SolicitorRoute
  '/trust': typeof TrustRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/judges': typeof AdminJudgesRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/playbooks/litigation': typeof PlaybooksLitigationRoute
  '/playbooks/matrix': typeof PlaybooksMatrixRoute
  '/portals/advertiser': typeof PortalsAdvertiserRoute
  '/portals/agency': typeof PortalsAgencyRoute
  '/portals/client': typeof PortalsClientRoute
  '/portals/professional': typeof PortalsProfessionalRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/providers/join': typeof ProvidersJoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advertise'
    | '/audit-log'
    | '/auth'
    | '/calendar'
    | '/cases'
    | '/collab'
    | '/connections'
    | '/court-docs'
    | '/donate'
    | '/employee'
    | '/feedback'
    | '/judges'
    | '/legislative'
    | '/portals'
    | '/pricing'
    | '/professionals'
    | '/reviews'
    | '/solicitor'
    | '/trust'
    | '/admin/employees'
    | '/admin/judges'
    | '/admin/providers'
    | '/employee/dashboard'
    | '/employee/tasks'
    | '/playbooks/litigation'
    | '/playbooks/matrix'
    | '/portals/advertiser'
    | '/portals/agency'
    | '/portals/client'
    | '/portals/professional'
    | '/providers/$id'
    | '/providers/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advertise'
    | '/audit-log'
    | '/auth'
    | '/calendar'
    | '/cases'
    | '/collab'
    | '/connections'
    | '/court-docs'
    | '/donate'
    | '/employee'
    | '/feedback'
    | '/judges'
    | '/legislative'
    | '/portals'
    | '/pricing'
    | '/professionals'
    | '/reviews'
    | '/solicitor'
    | '/trust'
    | '/admin/employees'
    | '/admin/judges'
    | '/admin/providers'
    | '/employee/dashboard'
    | '/employee/tasks'
    | '/playbooks/litigation'
    | '/playbooks/matrix'
    | '/portals/advertiser'
    | '/portals/agency'
    | '/portals/client'
    | '/portals/professional'
    | '/providers/$id'
    | '/providers/join'
  id:
    | '__root__'
    | '/'
    | '/advertise'
    | '/audit-log'
    | '/auth'
    | '/calendar'
    | '/cases'
    | '/collab'
    | '/connections'
    | '/court-docs'
    | '/donate'
    | '/employee'
    | '/feedback'
    | '/judges'
    | '/legislative'
    | '/portals'
    | '/pricing'
    | '/professionals'
    | '/reviews'
    | '/solicitor'
    | '/trust'
    | '/admin/employees'
    | '/admin/judges'
    | '/admin/providers'
    | '/employee/dashboard'
    | '/employee/tasks'
    | '/playbooks/litigation'
    | '/playbooks/matrix'
    | '/portals/advertiser'
    | '/portals/agency'
    | '/portals/client'
    | '/portals/professional'
    | '/providers/$id'
    | '/providers/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvertiseRoute: typeof AdvertiseRoute
  AuditLogRoute: typeof AuditLogRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  CasesRoute: typeof CasesRoute
  CollabRoute: typeof CollabRoute
  ConnectionsRoute: typeof ConnectionsRoute
  CourtDocsRoute: typeof CourtDocsRoute
  DonateRoute: typeof DonateRoute
  EmployeeRoute: typeof EmployeeRouteWithChildren
  FeedbackRoute: typeof FeedbackRoute
  JudgesRoute: typeof JudgesRoute
  LegislativeRoute: typeof LegislativeRoute
  PortalsRoute: typeof PortalsRouteWithChildren
  PricingRoute: typeof PricingRoute
  ProfessionalsRoute: typeof ProfessionalsRoute
  ReviewsRoute: typeof ReviewsRoute
  SolicitorRoute: typeof SolicitorRoute
  TrustRoute: typeof TrustRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminJudgesRoute: typeof AdminJudgesRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  PlaybooksLitigationRoute: typeof PlaybooksLitigationRoute
  PlaybooksMatrixRoute: typeof PlaybooksMatrixRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  ProvidersJoinRoute: typeof ProvidersJoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitor': {
      id: '/solicitor'
      path: '/solicitor'
      fullPath: '/solicitor'
      preLoaderRoute: typeof SolicitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals': {
      id: '/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof ProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals': {
      id: '/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof PortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislative': {
      id: '/legislative'
      path: '/legislative'
      fullPath: '/legislative'
      preLoaderRoute: typeof LegislativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges': {
      id: '/judges'
      path: '/judges'
      fullPath: '/judges'
      preLoaderRoute: typeof JudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/court-docs': {
      id: '/court-docs'
      path: '/court-docs'
      fullPath: '/court-docs'
      preLoaderRoute: typeof CourtDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab': {
      id: '/collab'
      path: '/collab'
      fullPath: '/collab'
      preLoaderRoute: typeof CollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/join': {
      id: '/providers/join'
      path: '/providers/join'
      fullPath: '/providers/join'
      preLoaderRoute: typeof ProvidersJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals/professional': {
      id: '/portals/professional'
      path: '/professional'
      fullPath: '/portals/professional'
      preLoaderRoute: typeof PortalsProfessionalRouteImport
      parentRoute: typeof PortalsRoute
    }
    '/portals/client': {
      id: '/portals/client'
      path: '/client'
      fullPath: '/portals/client'
      preLoaderRoute: typeof PortalsClientRouteImport
      parentRoute: typeof PortalsRoute
    }
    '/portals/agency': {
      id: '/portals/agency'
      path: '/agency'
      fullPath: '/portals/agency'
      preLoaderRoute: typeof PortalsAgencyRouteImport
      parentRoute: typeof PortalsRoute
    }
    '/portals/advertiser': {
      id: '/portals/advertiser'
      path: '/advertiser'
      fullPath: '/portals/advertiser'
      preLoaderRoute: typeof PortalsAdvertiserRouteImport
      parentRoute: typeof PortalsRoute
    }
    '/playbooks/matrix': {
      id: '/playbooks/matrix'
      path: '/playbooks/matrix'
      fullPath: '/playbooks/matrix'
      preLoaderRoute: typeof PlaybooksMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks/litigation': {
      id: '/playbooks/litigation'
      path: '/playbooks/litigation'
      fullPath: '/playbooks/litigation'
      preLoaderRoute: typeof PlaybooksLitigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/tasks': {
      id: '/employee/tasks'
      path: '/tasks'
      fullPath: '/employee/tasks'
      preLoaderRoute: typeof EmployeeTasksRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/dashboard': {
      id: '/employee/dashboard'
      path: '/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof EmployeeDashboardRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/judges': {
      id: '/admin/judges'
      path: '/admin/judges'
      fullPath: '/admin/judges'
      preLoaderRoute: typeof AdminJudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EmployeeRouteChildren {
  EmployeeDashboardRoute: typeof EmployeeDashboardRoute
  EmployeeTasksRoute: typeof EmployeeTasksRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeDashboardRoute: EmployeeDashboardRoute,
  EmployeeTasksRoute: EmployeeTasksRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface PortalsRouteChildren {
  PortalsAdvertiserRoute: typeof PortalsAdvertiserRoute
  PortalsAgencyRoute: typeof PortalsAgencyRoute
  PortalsClientRoute: typeof PortalsClientRoute
  PortalsProfessionalRoute: typeof PortalsProfessionalRoute
}

const PortalsRouteChildren: PortalsRouteChildren = {
  PortalsAdvertiserRoute: PortalsAdvertiserRoute,
  PortalsAgencyRoute: PortalsAgencyRoute,
  PortalsClientRoute: PortalsClientRoute,
  PortalsProfessionalRoute: PortalsProfessionalRoute,
}

const PortalsRouteWithChildren =
  PortalsRoute._addFileChildren(PortalsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvertiseRoute: AdvertiseRoute,
  AuditLogRoute: AuditLogRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  CasesRoute: CasesRoute,
  CollabRoute: CollabRoute,
  ConnectionsRoute: ConnectionsRoute,
  CourtDocsRoute: CourtDocsRoute,
  DonateRoute: DonateRoute,
  EmployeeRoute: EmployeeRouteWithChildren,
  FeedbackRoute: FeedbackRoute,
  JudgesRoute: JudgesRoute,
  LegislativeRoute: LegislativeRoute,
  PortalsRoute: PortalsRouteWithChildren,
  PricingRoute: PricingRoute,
  ProfessionalsRoute: ProfessionalsRoute,
  ReviewsRoute: ReviewsRoute,
  SolicitorRoute: SolicitorRoute,
  TrustRoute: TrustRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminJudgesRoute: AdminJudgesRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  PlaybooksLitigationRoute: PlaybooksLitigationRoute,
  PlaybooksMatrixRoute: PlaybooksMatrixRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  ProvidersJoinRoute: ProvidersJoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
